// This file is generated by Astro DB
declare module 'astro:db' {
	export const Board: import("@astrojs/db/runtime").Table<
		"Board",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Board","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Board","primaryKey":false,"optional":false}},"message":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"message","collection":"Board","primaryKey":false,"optional":false}},"created_at":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"created_at","collection":"Board","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}}}
	>;
}
